export const productsData = [
    {
        id: 1,
        name: 'EMBROIDERED SHIRT WITH 2 LEAF STRIPES NECKLACE SLIMFIT FORM SM160',
        image: "/assets/product/product-1.jpg",
        sub_image: ["/assets/product/product-1-1.jpg","/assets/product/product-1-2.jpg","/assets/product/product-1-3.jpg","/assets/product/product-1-4.jpg"],
        price: 67.24,
        rating: 4,
        sizes: ["S","M","L","XL","XXL"],
        colors: ["white", "black", "blue"],
        category: "Shirt",
        id_category: 3,
    },
    {
        id: 2,
        name: 'ROUND-NECKLACE T-SHIRT PRINTED WITH THE LETTERS STAY STRONG REGULAR FORM AT162 BLACK',
        image: "/assets/product/product-2.jpg",
        sub_image: ["/assets/product/product-2-1.jpg","/assets/product/product-2-2.jpg","/assets/product/product-2-3.jpg","/assets/product/product-2-4.jpg"],
        price: 43.48,
        rating: 4.5,
        sizes: ["S","M","L","XL","XXL"],
        colors: ["black", "white", "blue"],
        category: "T-Shirt",
        id_category: 2,
    },
    {
        id: 3,
        name: 'REGULAR SUMMER ESCAPE AT075 YELLOW T-SHIRT',
        image: "/assets/product/product-3.jpg",
        sub_image: ["/assets/product/product-3-1.jpg","/assets/product/product-3-2.jpg","/assets/product/product-3-3.jpg","/assets/product/product-3-4.jpg"],
        price: 60.9,
        rating: 4.5,
        sizes: ["S","M","L","XL","XXL"],
        colors: ["yellow", "black", "blue"],
        category: "T-Shirt",
        id_category: 2,
    },
    {
        id: 4,
        name: 'ECLECTIC PREP FORM REGULAR EMBROIDERED JEANS QJ109 BLUE DARK',
        image: "/assets/product/product-4.jpg",
        sub_image: ["/assets/product/product-4-1.jpg","/assets/product/product-4-2.jpg","/assets/product/product-4-3.jpg","/assets/product/product-4-4.jpg"],
        price: 31.37,
        rating: 4,
        sizes: ["29","30","31","32","33","34","35"],
        colors: ["black", "blue","gray"],
        category: "Jeans",
        id_category: 9,
    },
    {
        id: 5,
        name: 'PREMIUM SLIMFIT FORM RAYON FABRIC SLIM TROUSERS QT031 BLACK',
        image: "/assets/product/product-5.jpg",
        sub_image: ["/assets/product/product-5-1.jpg","/assets/product/product-5-2.jpg","/assets/product/product-5-3.jpg","/assets/product/product-5-4.jpg"],
        price: 98.49,
        rating: 5,
        sizes: ["29","30","31","32","33","34","35"],
        colors: ["black"],
        category: "Trouser",
        id_category: 8,
    },
    {
        id: 6,
        name: 'BLACK JEANS SHORTS WITH SILVER WASH CROSSROAD POCKET STRAIGHT FORM QS052',
        image: "/assets/product/product-6.jpg",
        sub_image: ["/assets/product/product-6-1.jpg","/assets/product/product-6-2.jpg","/assets/product/product-6-3.jpg","/assets/product/product-6-4.jpg"],
        price: 49.66,
        rating: 5,
        sizes: ["29","30","31","32","33","34","35"],
        colors: ["black", "blue"],
        category: "Shorts",
        id_category: 11,
    },
    {
        id: 7,
        name: 'PARACHUTE JACKET PRESSED WITH BOX REGULAR FORM AK065 BLACK',
        image: "/assets/product/product-7.jpg",
        sub_image: ["/assets/product/product-7-1.jpg","/assets/product/product-7-2.jpg","/assets/product/product-7-3.jpg","/assets/product/product-7-4.jpg"],
        price: 26.28,
        rating: 4.5,
        sizes: ["S","M","L","XL","XXL"],
        colors: ["black","#f2eae1"],
        category: "Jacket",
        id_category: 4,
    },
    {
        id: 8,
        name: 'DERBY SHOES GI021 BLACK',
        image: "/assets/product/product-8.jpg",
        sub_image: ["/assets/product/product-8-1.jpg","/assets/product/product-8-2.jpg","/assets/product/product-8-3.jpg","/assets/product/product-8-4.jpg"],
        price: 44.23,
        rating: 4,
        sizes: ["38","39","40","41","42","43","44","45"],
        colors: ["black"],
        category: "Leather Shoes",
        id_category: 15,
    },
    {
        id: 9,
        name: 'TENNIS CLUB MU010 WHITE EMBROIDERED BOOM CAP',
        image: "/assets/product/product-9.jpg",
        sub_image: ["/assets/product/product-9-1.jpg","/assets/product/product-9-2.jpg","/assets/product/product-9-3.jpg","/assets/product/product-9-4.jpg"],
        price: 67.22,
        rating: 4,
        sizes: ["Free size"],
        colors: ["white"],
        category: "Hat",
        id_category: 20,
    },
    {
        id: 10,
        name: 'CASUAL TX014 STOMACH BAG BLUE-DARK',
        image: "/assets/product/product-10.jpg",
        sub_image: ["/assets/product/product-10-1.jpg","/assets/product/product-10-2.jpg","/assets/product/product-10-3.jpg","/assets/product/product-10-4.jpg"],
        price: 54.33,
        rating: 4.5,
        sizes: ["Free size"],
        colors: ["black"],
        category: "Wallet",
        id_category: 23,
    },
    {
        id: 11,
        name: 'SLIMFIT FORM VEST AV031',
        image: "/assets/product/product-11.jpg",
        sub_image: ["/assets/product/product-11-1.jpg","/assets/product/product-11-2.jpg","/assets/product/product-11-3.jpg","/assets/product/product-11-4.jpg"],
        price: 42.12,
        rating: 4.5,
        sizes: ["S","M","L","XL","XXL"],
        colors: ["black"],
        category: "Vest",
        id_category: 5,
    },
    {
        id: 12,
        name: 'STRIPED HOODIE WITH EMBEDDED STRIPED LOGO ON Wrist REGULAR FORM AH007 BEIGE',
        image: "/assets/product/product-12.jpg",
        sub_image: ["/assets/product/product-12-1.jpg","/assets/product/product-12-2.jpg","/assets/product/product-12-3.jpg","/assets/product/product-12-4.jpg"],
        price: 51.3,
        rating: 5,
        sizes: ["S","M","L","XL","XXL"],
        colors: ["#f2eae1", "black"],
        category: "Hoodie",
        id_category: 6,
    },
    {
        id: 13,
        name: 'SIGNATURE SLIM KAKI PANTS WITH METAL TAG SLIMFIT FORM QK028 BEIGE',
        image: "/assets/product/product-13.jpg",
        sub_image: ["/assets/product/product-13-1.jpg","/assets/product/product-13-2.jpg","/assets/product/product-13-3.jpg","/assets/product/product-13-4.jpg"],
        price: 102.0,
        rating: 4,
        sizes: ["29","30","31","32","33","34","35"],
        colors: ["beige"],
        category: "Kaki pants",
        id_category: 10,
    },
    {
        id: 14,
        name: 'SLIMFIT KAKI PANTS QK018 GRAY',
        image: "/assets/product/product-14.jpg",
        sub_image: ["/assets/product/product-14-1.jpg","/assets/product/product-14-2.jpg","/assets/product/product-14-3.jpg","/assets/product/product-14-4.jpg"],
        price: 124.0,
        rating: 4,
        sizes: ["29","30","31","32","33","34","35"],
        colors: ["gray"],
        category: "Kaki pants",
        id_category: 10,
    },
    {
        id: 15,
        name: 'KAKI JOGGER PANTS WITH ELECTRIC WAIST WITH TRIANGLE LEATHER TAG REGULAR FORM JO016 BLACK',
        image: "/assets/product/product-15.jpg",
        sub_image: ["/assets/product/product-15-1.jpg","/assets/product/product-15-2.jpg","/assets/product/product-15-3.jpg","/assets/product/product-15-4.jpg"],
        price: 94.0,
        rating: 4.5,
        sizes: ["M","L","XL"],
        colors: ["black"],
        category: "Elastic pants",
        id_category: 12,
    },
    {
        id: 16,
        name: 'REGULAR FORM STRETCH JOGGER PANTS JO011 GROSS COLOR',
        image: "/assets/product/product-16.jpg",
        sub_image: ["/assets/product/product-16-1.jpg","/assets/product/product-16-2.jpg","/assets/product/product-16-3.jpg","/assets/product/product-16-4.jpg"],
        price: 112.0,
        rating: 4,
        sizes: ["M","L","XL"],
        colors: ["beige"],
        category: "Elastic pants",
        id_category: 12,
    },
    {
        id: 17,
        name: 'MICROFIBER LEATHER HAND STRAP SANDAL TPR SOLES - DE005 BLACK',
        image: "/assets/product/product-17.jpg",
        sub_image: ["/assets/product/product-17-1.jpg","/assets/product/product-17-2.jpg","/assets/product/product-17-3.jpg","/assets/product/product-17-4.jpg"],
        price: 77.0,
        rating: 5,
        sizes: ["38","39","40","41","42","43","44","45"],
        colors: ["black"],
        category: "Sandals",
        id_category: 14,
    },
    {
        id: 18,
        name: 'MICROFIBER LEATHER SLANDERS WITH HUSK SOLES DE003 BLACK',
        image: "/assets/product/product-18.jpg",
        sub_image: ["/assets/product/product-18-1.jpg","/assets/product/product-18-2.jpg","/assets/product/product-18-3.jpg","/assets/product/product-18-4.jpg"],
        price: 87.0,
        rating: 4,
        sizes: ["38","39","40","41","42","43","44","45"],
        colors: ["beige"],
        category: "Leather slippers",
        id_category: 16,
    },
    {
        id: 19,
        name: 'NEEDLE HEAD BELT TL182.',
        image: "/assets/product/product-19.jpg",
        sub_image: ["/assets/product/product-19-1.jpg","/assets/product/product-19-2.jpg","/assets/product/product-19-3.jpg","/assets/product/product-19-4.jpg"],
        price: 34.33,
        rating: 4.5,
        sizes: ["Free size"],
        colors: ["black"],
        category: "Belt",
        id_category: 22,
    },
    {
        id: 20,
        name: 'ALRAN LEATHER HANDWALLET BV054',
        image: "/assets/product/product-20.jpg",
        sub_image: ["/assets/product/product-20-1.jpg","/assets/product/product-20-2.jpg","/assets/product/product-20-3.jpg","/assets/product/product-20-4.jpg"],
        price: 30.2,
        rating: 4,
        sizes: ["Free size"],
        colors: ["black"],
        category: "Leather wallet",
        id_category: 23,
    },
    {
        id: 21,
        name: 'SHORT SHORT SOCKS HORIZONTAL STRIPED TEXTILE VENTILATED COTTON OBSTRUCTION WHITE VO129',
        image: "/assets/product/product-21.jpg",
        sub_image: ["/assets/product/product-21-1.jpg","/assets/product/product-21-2.jpg","/assets/product/product-21-3.jpg","/assets/product/product-21-4.jpg"],
        price: 2.2,
        rating: 4,
        sizes: ["Free size"],
        colors: ["white"],
        category: "Socks",
        id_category: 21,
    },
    {
        id: 22,
        name: 'VO127 ABSORBENT COTTON HIGH-NECKLACE SPORTS SOCKS BLACK',
        image: "/assets/product/product-22.jpg",
        sub_image: ["/assets/product/product-22-1.jpg","/assets/product/product-22-2.jpg","/assets/product/product-22-3.jpg","/assets/product/product-22-4.jpg"],
        price: 2.7,
        rating: 4,
        sizes: ["Free size"],
        colors: ["black"],
        category: "Socks",
        id_category: 21,
    },
    {
        id: 23,
        name: 'LIGHT GREEN JEANS PRINTED WITH REAR POCKETS SLIMFIT QJ100',
        image: "/assets/product/product-23.jpg",
        sub_image: ["/assets/product/product-23-1.jpg","/assets/product/product-23-2.jpg","/assets/product/product-23-3.jpg","/assets/product/product-23-4.jpg"],
        price: 134.5,
        rating: 5,
        sizes: ["29","30","31","32","33","34","35"],
        colors: ["blue","black"],
        category: "Jeans",
        id_category: 9,
    },
    {
        id: 24,
        name: '2-POCKET SHIRT WITH EMBROIDERED M FORM SLIMFIT SM173 BEIGE',
        image: "/assets/product/product-24.jpg",
        sub_image: ["/assets/product/product-24-1.jpg","/assets/product/product-24-2.jpg","/assets/product/product-24-3.jpg","/assets/product/product-24-4.jpg"],
        price: 75.8,
        rating: 4,
        sizes: ["S","M","L","XL"],
        colors: ["beige"],
        category: "Shirt",
        id_category: 3,
    },
]

export const productCart = [
    {
        id: 1,
        size: "L",
        quantity: 1,
        color: "White",
    },
    {
        id: 2,
        size: "M",
        quantity: 2,
        color: "Black",
    },
    {
        id: 3,
        size: "M",
        quantity: 1,
        color: "Yellow",
    },
    {
        id: 4,
        size: "30",
        quantity: 1,
        color: "Black",
    },
]