export const productsData = [
    {
        id: 1,
        name: 'Áo Thun Nam Basic Cotton',
        image: "/assets/product/product-1.jpg",
        sub_image: ["/assets/product/product-1-1.jpg","/assets/product/product-1-2.jpg","/assets/product/product-1-3.jpg","/assets/product/product-1-4.jpg"],
        price: 67.24,
        rating: 4,
        sizes: ["S","M","L","XL","XXL"],
        colors: ["white", "black", "blue"],
        category: "Shirt",
    },
    {
        id: 2,
        name: 'Áo Thun Nam Basic Cotton',
        image: "/assets/product/product-2.jpg",
        sub_image: ["/assets/product/product-2-1.jpg","/assets/product/product-2-2.jpg","/assets/product/product-2-3.jpg","/assets/product/product-2-4.jpg"],
        price: 43.48,
        rating: 4.5,
        sizes: ["S","M","L","XL","XXL"],
        colors: ["white", "black", "blue"],
        category: "T-Shirt",
    },
    {
        id: 3,
        name: 'Áo Thun Nam Basic Cotton',
        image: "/assets/product/product-3.jpg",
        sub_image: ["/assets/product/product-3-1.jpg","/assets/product/product-3-2.jpg","/assets/product/product-3-3.jpg","/assets/product/product-3-4.jpg"],
        price: 60.9,
        rating: 4.5,
        sizes: ["S","M","L","XL","XXL"],
        colors: ["yellow", "black", "blue"],
        category: "T-Shirt",
    },
    {
        id: 4,
        name: 'Áo Thun Nam Basic Cotton',
        image: "/assets/product/product-4.jpg",
        sub_image: ["/assets/product/product-4-1.jpg","/assets/product/product-4-2.jpg","/assets/product/product-4-3.jpg","/assets/product/product-4-4.jpg"],
        price: 31.37,
        rating: 4,
        sizes: ["29","30","31","32","33","34","35"],
        colors: ["black", "blue","gray"],
        category: "Jeans",
    },
    {
        id: 5,
        name: 'Áo Thun Nam Basic Cotton',
        image: "/assets/product/product-5.jpg",
        sub_image: ["/assets/product/product-5-1.jpg","/assets/product/product-5-2.jpg","/assets/product/product-5-3.jpg","/assets/product/product-5-4.jpg"],
        price: 98.49,
        rating: 5,
        sizes: ["29","30","31","32","33","34","35"],
        colors: ["black"],
        category: "Trouser",
    },
    {
        id: 6,
        name: 'Áo Thun Nam Basic Cotton',
        image: "/assets/product/product-6.jpg",
        sub_image: ["/assets/product/product-6-1.jpg","/assets/product/product-6-2.jpg","/assets/product/product-6-3.jpg","/assets/product/product-6-4.jpg"],
        price: 49.66,
        rating: 5,
        sizes: ["29","30","31","32","33","34","35"],
        colors: ["black", "blue"],
        category: "Shorts",
    },
    {
        id: 7,
        name: 'Áo Thun Nam Basic Cotton',
        image: "/assets/product/product-7.jpg",
        sub_image: ["/assets/product/product-7-1.jpg","/assets/product/product-7-2.jpg","/assets/product/product-7-3.jpg","/assets/product/product-7-4.jpg"],
        price: 26.28,
        rating: 4.5,
        sizes: ["S","M","L","XL","XXL"],
        colors: ["black","#f2eae1"],
        category: "Jacket",
    },
    {
        id: 8,
        name: 'Áo Thun Nam Basic Cotton',
        image: "/assets/product/product-8.jpg",
        sub_image: ["/assets/product/product-8-1.jpg","/assets/product/product-8-2.jpg","/assets/product/product-8-3.jpg","/assets/product/product-8-4.jpg"],
        price: 44.23,
        rating: 4,
        sizes: ["38","39","40","41","42","43","44","45"],
        colors: ["black"],
        category: "Leather Shoes",
    },
    {
        id: 9,
        name: 'Áo Thun Nam Basic Cotton',
        image: "/assets/product/product-9.jpg",
        sub_image: ["/assets/product/product-9-1.jpg","/assets/product/product-9-2.jpg","/assets/product/product-9-3.jpg","/assets/product/product-9-4.jpg"],
        price: 67.22,
        rating: 4,
        sizes: ["Free size"],
        colors: ["white"],
        category: "Hat",
    },
    {
        id: 10,
        name: 'Áo Thun Nam Basic Cotton',
        image: "/assets/product/product-10.jpg",
        sub_image: ["/assets/product/product-10-1.jpg","/assets/product/product-10-2.jpg","/assets/product/product-10-3.jpg","/assets/product/product-10-4.jpg"],
        price: 54.33,
        rating: 4.5,
        sizes: ["Free size"],
        colors: ["white"],
        category: "Wallet",
    },
    {
        id: 11,
        name: 'Áo Thun Nam Basic Cotton',
        image: "/assets/product/product-11.jpg",
        sub_image: ["/assets/product/product-11-1.jpg","/assets/product/product-11-2.jpg","/assets/product/product-11-3.jpg","/assets/product/product-11-4.jpg"],
        price: 42.12,
        rating: 4.5,
        sizes: ["S","M","L","XL","XXL"],
        colors: ["black"],
        category: "Vest",
    },
    {
        id: 12,
        name: 'Áo Thun Nam Basic Cotton',
        image: "/assets/product/product-12.jpg",
        sub_image: ["/assets/product/product-12-1.jpg","/assets/product/product-12-2.jpg","/assets/product/product-12-3.jpg","/assets/product/product-12-4.jpg"],
        price: 51.3,
        rating: 5,
        sizes: ["S","M","L","XL","XXL"],
        colors: ["#f2eae1", "black"],
        category: "Hoodie",
    },
]

export const productCart = [
    {
        id: 1,
        size: "L",
        quantity: 1,
        color: "White",
    },
    {
        id: 2,
        size: "M",
        quantity: 2,
        color: "Black",
    },
    {
        id: 3,
        size: "M",
        quantity: 1,
        color: "Yellow",
    },
    {
        id: 4,
        size: "30",
        quantity: 1,
        color: "Black",
    },
]